### ISSUE TITLE
I got error with your provided example

### ISSUE THREAD

**Issue by serunis** [colinxu2020/slhdsa#1]
pub = PublicKey.from_digest(digest)  # generate public key
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PublicKey.from_digest() missing 1 required positional argument: 'par'

**Comment by serunis** [comment]
oh one of followings, I understand

from slhdsa.lowlevel.parameters import sha2_128f, sha2_128s, sha2_192f, sha2_192s, sha2_256f, sha2_256s  # noqa: F401
from slhdsa.lowlevel.parameters import shake_128f, shake_128s, shake_192f, shake_192s, shake_256f, shake_256s  # noqa: F401

**Comment by colinxu2020** [comment]
Sorry for the mistake in the document, I'll fix it as soon as possible.

**Comment by colinxu2020** [comment]
Sorry for the mistake in the docs, I'll fix it as soon as possible.

**Comment by colinxu2020** [comment]
The document on github has been fixed recently, due to some build issue, I can't publish it to pypi now, I'll publish it after I fix the problems.
